// looping condition control repeatative in code and are essential for automatic repeatative tasks
// iska kaam h ki ye code ko repeating condition ke saath tn tkk repeat krwata h jb tk value uske barabr ya fir usse badi na a jaye 

// for example ->
for(initializer; conditional; increase/decrease){
    // \
    // print the value 1 -> 5
    // for(let i = 1; i <= 5; i++){1=>2=>3=>4=>5=>6
        console.log(i);1,2,3,4,5.
    }
// }
console.log("the loop is ended!");
console.log("even!");
// for(let i = 2, i<= 10; i += 2){(2=>4=>6=>8=>10=>12)
console.log(i);
// }
console.log("odd!");
// for(let i = 2, i<= 10, i += 2){(1=>3=>5=>7=>9=>11)
    console.log(i);

// }
console.log("loop is ended!");

// initializer => part off setup the variable of 10 used to Counter.
// it run only once at the start of loop .
// (let i = 0); 

// purpose:- establishes the initial state before the loop begins.
// if i try to print value of (i) 1 to 10 but i is not equal to 5 & 8 and i try to not print the value of 5 & 8 then:
// for(let i = 1, i <= 10, i != 8)
    console.log(i);
output=>(1,2,3,4,6,7,9,10) 

// use case of (CONDITION)=> iska use loop ke andrr hota h jb hum kisi specific condition pe current iteration ko skip karke next iteration prr jana hota h.
// when we print any no b/w 1 to 10 but we skip no 6 the we use the (continue)

// for(let i = 0 , i <= 10, i++){
    if (i === 6)
        // continue;
// }
console.log(i);
output =>(0,1,2,3,4,5,7,8,9) 